server:
  port: ${TODO_SERVICE_PORT:8091}

spring:
  application:
    name: todo
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
  datasource:
    url: ${TODO_SERVICE_DB_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
