spring.application.name=taskbot-api-gateway

server.port=8080
server.servlet.context-path=/

microservices.notification-service.url=http://notification-service:8093
microservices.task-service.url=http://todo-service:8091
microservices.user-service.url=http://user-service:8090
microservices.documentation-service.url=http://documentation-service:8092
microservices.contact-service.url=http://contact-service:8094

logging.level.ru.itis.migrants.apigateway.controller:debug