server:
  port: ${DOCUMENTATION_SERVICE_PORT:8084}

spring:
  application:
    name: documentation-service

  datasource:
    url: ${DOCUMENTATION_DB_URL:jdbc:postgresql://localhost:5436/documentation_db}
    username: ${DOCUMENTATION_DB_USER:documentation_user}
    password: ${DOCUMENTATION_DB_PASSWORD:documentation_password}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
