server:
  port: 8081

spring:
  application:
    name: bot

  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]

  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USER}
    password: ${RABBIT_MQ_PASSWORD}


clients:
  gateway:
    base-url: http://localhost:8080
    connect-timeout: 5s
    read-timeout: 10s

property:
  rabbitmq:
    queue: notification.push.queue
    exchange: notification.topic.exchange
    push-key: notification.push.*

app:
  telegram:
    url: https://api.telegram.org/bot
    token: ${TELEGRAM_TOKEN}
    update-listener-sleep: 1s
    debug: false
  timezone: Asia/Yekaterinburg

logging:
  level:
    ru.itis.migrants.bot.commands: debug
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.http.converter.json: TRACE