server:
  port: 8081

spring:
  application:
    name: bot

clients:
  gateway:
    base-url: http://localhost:8080
    connect-timeout: 5s
    read-timeout: 10s


app:
  telegram:
    url: https://api.telegram.org/bot
    token: ${TELEGRAM_TOKEN}
    update-listener-sleep: 1s
    debug: false
  timezone: Asia/Yekaterinburg

logging:
  level:
    ru.itis.migrants.bot.commands: debug
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.http.converter.json: TRACE