server:
  port: ${USER_SERVICE_PORT:8090}

spring:
  application:
    name: user-service
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
  datasource:
    url: ${USER_SERVICE_DB_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
starter:
  logging:
    enabled: true
    pointcuts:
      - "execution(* ru.itis.migrants.userservice.service.*.*(..))"
      - "execution(* ru.itis.migrants.userservice.controller.*.*(..))"
    file:
      directory: logs
      enabled: true
      pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
      timestamp-pattern: "yyyy-MM-dd_HH-mm-ss"
