package ru.itis.migrants.bot.models.enums;

public enum DialogState {
    IDLE,
    AWAITING_TITLE,
    AWAITING_DEADLINE,
    AWAITING_NOTIFY_PERIOD,

    AWAITING_CONTACT_NAME,
    AWAITING_PHONE,
    AWAITING_EMAIL,
    AWAITING_COMPANY,
    AWAITING_NOTE,

    AWAITING_NOTIFICATION_TITLE,
    AWAITING_NOTIFICATION_TYPE,
    AWAITING_NOTIFICATION_DATETIME,
    AWAITING_NOTIFICATION_INTERVAL
}
